### PR TITLE
Implement AMP for Quadrupeds

### PR DESCRIPTION
**Pull request by dtch1997**
Continuation of this work: https://github.com/dtch1997/ASE/pull/1
Related issue: https://github.com/nv-tlabs/ASE/issues/26

### CODE REVIEW

**Comment by dtch1997** [comment]
QuadrupedAMP looks good now. Now we just need to hook it up to the AMP algorithm.

**Comment by dtch1997** [comment]
Okay, so QuadrupedAMP can now be run with the standard training algorithm (PPO). Since I didn't override the reward function yet, the behaviour as it stands should be exactly the same as the baseline Quadruped task trained with PPO. Will test shortly.

**Comment by dtch1997** [comment]
Currently, implementation doesn't work because `Quadruped` lacks some analogous functionality implemented in `HumanoidAMPBase`. It may be worthwhile to simply re-start from scratch with a new `QuadrupedAMPBase` class and change QuadrupedAMP to inherit from that.

**Comment by dtch1997** [comment]
For reference, HumanoidAMP can be successfully trained like this: 
https://user-images.githubusercontent.com/25474937/214547717-67e61ab5-0c66-43de-bf1b-bc719d7734af.mp4

**Comment by dtch1997** [comment]
Rough notes:
- Increase training epochs of QuadrupedAMP to be similar to HumanoidAMP
- Check that reference state initialization is done properly in QuadrupedAMP

**Comment by dtch1997** [comment]
Okay I guess we can't get around it. I have to implement QuadrupedAMPBase in order to be confident that QuadrupedAMP functionality is close to HumanoidAMP

**Comment by dtch1997** [comment]
The implementation of reference state initialization seems to be bugged. (Below: Video with option 'Random' which should select a random point in the mo-cap to initialize the state) 

https://user-images.githubusercontent.com/25474937/214640222-c3596e6f-c789-468b-8b23-4972ec680b58.mp4

**Comment by dtch1997** [comment]
After updating to a higher-quality dog trot motion capture, the reference state initialization looks better. However we still get some artifacts due to not correctly adjusting the root pos before initializing. 

https://user-images.githubusercontent.com/25474937/214649819-4d585187-cb71-45ee-8c92-2148b7584874.mp4

**Comment by dtch1997** [comment]
Reference state initialization isn't playing nicely with early termination condition. At the moment, environment seems to reset immediately upon reference state init. Curiously, the first init seems to be fine. 

Result of printing `progress_buf` at each step in `post_physics_step`: 
```
...
RunningMeanStd:  (74,)
tensor([0, 0], device='cuda:0')
disc_pred:  -0.47064626 0.97052145
fps step: 67.4 fps total: 30.3
tensor([39, 39], device='cuda:0')
tensor([1, 1], device='cuda:0')
tensor([1, 1], device='cuda:0')
tensor([1, 1], device='cuda:0')
tensor([1, 1], device='cuda:0')
tensor([1, 1], device='cuda:0')
tensor([1, 1], device='cuda:0')
tensor([1, 1], device='cuda:0')
tensor([1, 1], device='cuda:0')
disc_pred:  0.7767504 2.310234
fps step: 106.9 fps total: 36.9
tensor([1, 1], device='cuda:0')
```

**Comment by dtch1997** [comment]
Reference state initialization seems to work now! 

https://user-images.githubusercontent.com/25474937/214658255-c4f15134-231c-432c-9516-033615db3376.mp4

**Comment by dtch1997** [comment]
Good initial results. However, robot seems to be 'bouncing'. This could be due to several things:
- [ ] Action scale being too high (I set it to 2.0 to ensure full range of motion)
- [ ] URDF not being correct (I took it from the motion_imitation repo)

**Comment by dtch1997** [comment]
At the moment, training result is like this. 

https://user-images.githubusercontent.com/25474937/214832741-d976fa54-94d2-405a-a4a7-f768418db600.mp4

**Comment by dtch1997** [comment]
Managed to implement a visualization of the motion-capture. For reference, this is the HumanoidAMP motion-capture and the corresponding learned agent. 

https://user-images.githubusercontent.com/25474937/214893744-469f6ef8-60cf-4868-8d64-da8a4bc21665.mp4

**Comment by dtch1997** [comment]
Implemented the same thing for QuadrupedAMP in https://github.com/dtch1997/IsaacGymEnvs/commit/b4e4b1cbddd066d10f9383bbc6465a8515a80b71

From the video, it becomes clear that the reference motion is somehow 'suspended in the air' relative to the real robot. Interim solution is to simply remove `root_h` as an amp_observation. Long-term solution may be to somehow sync the reference and real heights. 

https://user-images.githubusercontent.com/25474937/214926793-d2d9f5a5-9f13-4db8-ab07-200a38619e45.mp4

**Comment by dtch1997** [comment]
Note to self: In `build_amp_observations`, we have this line: 
```
    if (local_root_obs):
        root_rot_obs = quat_mul(heading_rot, root_rot)
    else:
        root_rot_obs = root_rot
```

Question to self: Is this a bug in the implementation? It seems like we should multiply root_rot by heading_rot and not the other way around. Need to check.

**Comment by dtch1997** [comment]
Some good signs of life here. I think the only issue that remains is the reference state initialization using the mo-cap height, which we should try to eliminate (because it makes the robot fall too easily) 

https://user-images.githubusercontent.com/25474937/215109364-b59469a8-8d66-4738-ab81-6d5e25b55a58.mp4

**Comment by dtch1997** [comment]
At the moment, I have a suspicion that AMP method is overly sensitive to the quality of the motion-capture. For my own motion-capture, which is relatively lower quality, the discriminator seems to be able to learn almost immediately how to distinguish real and fake, which suggests some simple 'cheating' method. 

This could be tested by corrupting the HumanoidAMP version with noise and testing whether that breaks the implementation.

**Comment by dtch1997** [comment]
TODO: Investigate using motions from this repo (more recent and high-quality): https://github.com/xbpeng/DeepMimic/tree/master/data/motions

**Comment by dtch1997** [comment]
Updated results for trotting and spinning available here; https://drive.google.com/drive/folders/1FIGaLlNZworGI8zaO80pHTwY3XbxuoxM?usp=sharing

Uploading trot_viz_ref.mp4…

**Comment by RAVaught** [comment]
This is really great work :)

**Pull request merged**
